---
- name: Configure MariaDB Repository
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.2/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
    state: present

- name: Install mariadb
  yum:
    name: ['MariaDB-server', 'MariaDB']
    state: present

# Configure Memcached.
- name: Copy my.cnf configuration.
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart mariadb

- name: Ensure service is started
  service: 
    name: mariadb 
    state: started 
    enabled: yes

- name: Install python-mysql module dependancy.
  easy_install:
    name: PyMySQL
    state: present

- name: Create application databases when they exist
  mysql_db:
    name: "{{ item.db_name }}"
    state: present
  loop: "{{ application_databases }}"
  register: db_created
  when: application_databases is defined

- name: Create database user and privileges.
  mysql_user:
    name: "{{ item.db_user }}"
    password: "{{ item.db_passwd }}"
    priv: "{{ item.db_name }}.*:ALL"
    state: present
  loop: "{{ application_databases }}"
  when: application_databases is defined

- name: Import application database schemas if they exist.
  mysql_db:
    state: import
    name: "{{ item.db_name }}"
    target: "{{ item.db_archive }}"
  loop: "{{ application_databases }}"
  when: application_databases is defined and enable_devel_mode == True and db_created.changed