---
- name: Install mariadb
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server
    - mariadb

# Configure Memcached.
- name: Copy my.cnf configuration.
  template:
    src: mmy.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart mysql

- name: Ensure service is started
  service: name=mariadb state=started enabled=yes